[build]
  publish = "exampleSite/public"
  command = "set +e && cd exampleSite && hugo --gc --themesDir ../.. -b https://innovation-tech-junction.co/"
  
[build.environment]
  HUGO_VERSION = "0.115.3"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"