[build]
publish = "public"
command = "hugo -v --minify --gc -b https://innovation-tech-junction.co/"

[build.environment]
HUGO_VERSION = "0.115.3"
HUGO_BASEURL = "/"

[[headers]]
for = "/*" # This defines which paths this specific [[headers]] block will cover.

[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "same-origin"
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
